services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-ubiquitous-composer
    container_name: react-ubiquitous-composer
    volumes:
      - '.:/var/www/html'
    working_dir: /var/www/html
    tty: true
